#!/usr/bin/env python3
"""Assemble results/REPORT.md from results/eval_*.json and results/verification_*.json (every number in the README comes from here).
  python scripts/make_report.py
"""
import json
from pathlib import Path

from_dir = Path("results")
SYSTEMS = [("ocr_rules", "OCR + rules (PaddleOCR)"), ("zeroshot", "Qwen2.5-VL-3B zero-shot"), ("qlora", "Qwen2.5-VL-3B QLoRA")]
FIELDS = ["issuer_name", "registration_number", "issue_date", "recipient_name", "invoice_number", "tax_included", "grand_total", "items", "totals"]
ci = lambda c: "-" if c is None or c.get("mean") is None else (f"{100 * c['mean']:.1f} [{100 * c['cp_lo']:.1f}, {100 * c['cp_hi']:.1f}] ({c['k']}/{c['n']})" if "k" in c else f"{100 * c['mean']:.1f} [{100 * c['lo']:.1f}, {100 * c['hi']:.1f}]")
pct = lambda c: "-" if c is None or c.get("mean") is None else f"{100 * c['mean']:.1f}"


def load(path):
    p = from_dir / path
    return json.loads(p.read_text()) if p.exists() else None


out = ["# Results report (generated by scripts/make_report.py)\n"]
for split, title in (("test", "Test (seen templates, unseen issuers)"), ("holdout", "Hold-out (unseen templates and issuers)")):
    out.append(f"## Extraction: {title}\n")
    out.append("| system | n | whole invoice exact [95% CI] | " + " | ".join(FIELDS) + " |")
    out.append("|---|---|---|" + "---|" * len(FIELDS))
    for key, name in SYSTEMS:
        e = load(f"eval_{key}_{split}.json")
        if e:
            out.append(f"| {name} | {e['n']} | {ci(e['exact'])} | " + " | ".join(pct(e["fields"][f]) for f in FIELDS) + " |")
    out.append("")
    out.append("Exact match by layout:\n")
    out.append("| system | horizontal | vertical |\n|---|---|---|")
    for key, name in SYSTEMS:
        e = load(f"eval_{key}_{split}.json")
        if e:
            lay = e["exact_by_layout"]
            out.append(f"| {name} | {ci(lay.get('horizontal'))} | {ci(lay.get('vertical'))} |")
    out.append("")
for split, title in (("test", "Test"), ("holdout", "Hold-out (unseen templates)")):
    for key, name in SYSTEMS:
        v = load(f"verification_{key}_{split}.json")
        if not v:
            continue
        out.append(f"## Verification layers: {name}, {title} (n={v['n']}, clean {v['n_clean']}, with a document issue {v['n_issue']})\n")
        out.append("| layers | automation rate | residual error (all invoices) | residual among approved | of which covered fields | of which uncovered fields | wrong extractions caught | document issues flagged |\n|---|---|---|---|---|---|---|---|")
        for lname, lv in v["levels"].items():
            out.append(f"| {lname} | {ci(lv['automation_rate'])} | {ci(lv['residual_error_all'])} | {ci(lv['residual_error_among_approved'])} | "
                       f"{ci(lv['residual_covered_among_approved'])} | {ci(lv['residual_uncovered_among_approved'])} | {ci(lv['wrong_extractions_caught'])} | {ci(lv['document_issues_flagged'])} |")
        out.append(f"\nApproved but still wrong, by field: {v['approved_but_wrong_by_field']}\n")
        out.append("Injected issue caught by the intended check: " + ", ".join(f"{k} {100 * c['mean']:.0f}% (n={c['n']})" for k, c in v["issue_caught_by_intended_check"].items()) + "\n")
Path("results/REPORT.md").write_text("\n".join(out) + "\n")
print("wrote results/REPORT.md", len(out), "lines")
